Update challenge10.md
git rebase main
dropping 2e5ff02edb91dcae478f45334f14da830564b6c7 9 -- patch contents already upstream
Auto-merging Challenges/challenge10.md
CONFLICT (add/add): Merge conflict in Challenges/challenge10.md
error: could not apply f581309... add 10th challenge
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply f581309... add 10th challenge